{% set version = "2.7.8" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-wdi
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/WDI_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/WDI/WDI_{{ version }}.tar.gz
  sha256: acf56a705d38cadda108a1b9f3a8ce22090bac57c44f1b6ffd23c43d3c39ede0

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-jsonlite
  run:
    - r-base
    - r-jsonlite

test:
  commands:
    - $R -e "library('WDI')"           # [not win]
    - "\"%R%\" -e \"library('WDI')\""  # [win]

about:
  home: https://www.github.com/vincentarelbundock/WDI
  license: GPL-3.0-only
  summary: Search, extract and format data from the World Bank's World Development Indicators.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: WDI
# Title: World Development Indicators (World Bank)
# Description: Search, extract and format data from the World Bank's World Development Indicators.
# Author: Vincent Arel-Bundock <vincent.arel-bundock@umontreal.ca>
# Maintainer: Vincent Arel-Bundock <vincent.arel-bundock@umontreal.ca>
# LazyData: yes
# Type: Package
# LazyLoad: yes
# Encoding: UTF-8
# Version: 2.6.0
# URL: https://www.github.com/vincentarelbundock/WDI
# Date: 2019-03-02
# Depends: R (>= 3.1.0)
# Imports: RJSONIO
# Suggests: tidyr (>= 0.8.0), testthat
# RoxygenNote: 6.1.1
# License: GPL-3
# NeedsCompilation: no
# Packaged: 2019-03-03 03:27:57 UTC; vincent
# Repository: CRAN
# Date/Publication: 2019-03-03 21:00:16 UTC
