appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: OOl0tbbXwoWe+LiNBm1w16PTQ8511pCCU4uptvXiyAdb/m2Mefn5708ivEafff7yelEbKHZ2p4LSd1DU2xMzcDmhg9BsRbtqP6LJbv4mFHQYaW6ZY3ggJUn/SjtCswS6qIJsaIUhYQ38H7vvh+rqZCbXywsGw5lQVOt+Qsy0gIGiEZZSBOkRFaJmY0Pj9tMKMIFbUjaIb4taO/Zg/vIA+/IUVPmlrgvu7e1/+E1XI2HMpdG0hAHm2w4Dbza+Js0rUtsRCe7xN5miIjK681qlCCCvE6VsgHIFFJ5BcSKgJOzugjV//qMs6Un0g6NnFjpevi/KQNIRi1Vvbz+1IBgwaY19yE47c5FZes1lUtrWILb7HPnjHRJWAAB9QzlkBbPgzeuTIE9O+6fNFApYgGqkxFHYk+mqHgmVNn8QQn+j3KCxX4/Cipt7qzBmxjXtltEeFraR5FkYDx7P0VClAXevLtcly9bTA1q4UchWJ1en0mVUhn3CcjL98h5UCkgqIy6PF2GhY9mIvrZraVi/ty74udgDvd1vAyH1oWByqvviOFk9Wrdf/tCZLyKo5WtyfbCjxWwVOhS9FLZzZdmK0ojXzRS6DHUV+VeMGIIZjRm1CyljWd37ouuk5DhMJ/5AJ63s40QLNXzmTY3V8CfmZkecfZioNziYlljLtgOPs0nECOY=}
